version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker 
      - image: php:7.2-cli # ...with this image as the primary container; this is where all `steps` will run
    working_directory: ~/project # directory where steps will run
    steps: # a set of executable commands
      - run: apt-get update  
      - run: apt-get -y install git zip unzip
      - checkout # special step to check out source code to working directory
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: composer install -n --prefer-dist
      - run: vendor/bin/phpunit --configuration phpunit.xml
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor