version: 2 # use CircleCI 2.0
jobs:
  build:
    docker: 
      - image: php:7.2-cli
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        environment:
         - cluster.name: es-test-cluster
         - xpack.security.enabled: false
         - transport.host: localhost
         - network.host: 127.0.0.1
         - http.port: 9200
         - discovery.type: single-node
    working_directory: ~/project
    steps:
      - run: apt-get update  
      - run: apt-get -y install git zip unzip
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - run: vendor/bin/phpcs --standard=PSR12 --ignore=vendor/* ./
      - run: vendor/bin/phpmd ./ text cleancode,codesize,controversial,design,unusedcode,naming --exclude vendor
      - run: vendor/bin/phpunit
      - run: curl -XGET localhost:9200
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor