version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: kibana:6.8.2
    ports:
      - "5601:5601"
  php:
    build: 'docker/php'
